---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: @IP@
  bindPort: 6443
nodeRegistration:
  criSocket: /run/containerd/containterd.sock
  #kubeletExtraArgs:
  #  cloud-provider: aws
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "@ELB_DNS_PRIV@:6443"
apiServer:
  certSANs:
  - @IP@
  - @ELB_DNS_PRIV@
  - @ELB_DNS_PUB@
  extraArgs:
   cloud-provider: aws
controllerManager:
  extraArgs:
    cloud-provider: aws
clusterName: "@CLUSTER_NAME@"
networking:
  dnsDomain: "cluster.local"
  podSubnet: "@POD_SUBNET@"
  serviceSubnet: "@SERVICE_SUBNET@"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes: ""
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 5
clusterCIDR: "@POD_SUBNET@"
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: false
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 30s
kind: KubeProxyConfiguration
metricsBindAddress: 127.0.0.1:10249
mode: "ipvs"
nodePortAddresses: null
oomScoreAdj: -999
portRange: ""
resourceContainer: /kube-proxy
udpIdleTimeout: 250ms
